In [55]:
import pandas as pd 
from matplotlib import * 
import math 
import numpy as np
df = pd.read_csv('./vgsales.csv')
print (df.isna().sum())
dfShapeBefore = df.shape
predf = df 
df.dropna(inplace = True)
print(np.array(dfShapeBefore) - np.array(df.shape)) 
#so there is 307 missing values between the year clmn (nemerical var) and the publisher (categorical var)
# they may be missing due to problems during the transfer of data or because the are related to other missing data like how 
#the global sales is related to the eu + jp + na sales ... (MNAR)

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64
[307   0]

In [56]:
# the mean , median , quartiles of each numerical variable
#mean
rankMean = df.Rank.mean()
yearMean = df.Year.mean()
NASalesMean = df.NA_Sales.mean()
EUSalesMean = df.EU_Sales.mean()
JPSalesMean = df.JP_Sales.mean()
GlobalSalesMean = df.Global_Sales.mean()
#median
rankMedian = df.Rank.median()
yearMedian = df.Year.median()
NASalesMedian = df.NA_Sales.median()
EUSalesMedian = df.EU_Sales.median()
JPSalesMedian = df.JP_Sales.median()
GlobalSalesMedian = df.Global_Sales.median()
#quartiles 
rankQuantile = [df.Rank.quantile(0.25),df.Rank.quantile(.5),df.Rank.quantile(.75)]
yearQuantile = [df.Year.quantile(0.25),df.Year.quantile(.5),df.Year.quantile(.75)]
NASalesQuantile = [df.NA_Sales.quantile(.25),df.NA_Sales.quantile(.5),df.NA_Sales.quantile(0.75)]
EUSalesQuantile =  [df.EU_Sales.quantile(.25),df.EU_Sales.quantile(.5),df.EU_Sales.quantile(0.75)]
JPSalesQuantile = [df.JP_Sales.quantile(.25),df.JP_Sales.quantile(.5),df.JP_Sales.quantile(0.75)]
GlobalSalesQuantile = [df.Global_Sales.quantile(.25),df.Global_Sales.quantile(.5),df.Global_Sales.quantile(0.75)]

In [57]:
#outliers 
df['NAsales_zscore']=(df.NA_Sales-df.NA_Sales.mean() ) / df.NA_Sales.std()
df['EUsales_zscore']=(df.EU_Sales-df.EU_Sales.mean() ) / df.EU_Sales.std()
df['JPsales_zscore']=(df.JP_Sales-df.JP_Sales.mean() ) / df.JP_Sales.std()
df['Globalsales_zscore']=(df.Global_Sales-df.Global_Sales.mean() ) / df.Global_Sales.std()
df['Rank_zscore']=(df.Rank-df.Rank.mean() ) / df.Rank.std()
df['Year_zscore']=(df.Year-df.Year.mean() ) / df.Year.std()
pre_df = df 
df = df[(abs(df['Rank_zscore'])>1 )
     &(df['Rank_zscore'] < df['Rank_zscore'].max()) 
     & (abs(df['Year_zscore'])> 1) 
     &  (abs(df['Globalsales_zscore'])>1)
     & (abs(df['JPsales_zscore'])> 1)
     & (abs(df['NAsales_zscore'])> 1) 
     & (abs(df['EUsales_zscore'])> 1)
     & (df['Rank_zscore'] < df['Rank_zscore'].max()) 
     & (df['NAsales_zscore'] < df['NAsales_zscore'].max()) 
     & (df['EUsales_zscore'] < df['EUsales_zscore'].max())
     &(df['JPsales_zscore'] < df['JPsales_zscore'].max())
     &(df['Globalsales_zscore'] < df['Globalsales_zscore'].max()) 
     &(df['Year_zscore'] < df['Year_zscore'].max())]

In [61]:
print(pre_df.info)
print(df.drop(columns=['NAsales_zscore','EUsales_zscore','JPsales_zscore','Globalsales_zscore','Rank_zscore','Year_zscore']).info)
#16143 row has been dropes after removing the outliers

<bound method DataFrame.info of         Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii
1          2                                 Super Mario Bros.      NES
2          3                                    Mario Kart Wii      Wii
3          4                                 Wii Sports Resort      Wii
4          5                          Pokemon Red/Pokemon Blue       GB
...      ...                                               ...      ...
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA
16594  16597                     Men in Black II: Alien Escape       GC
16595  16598  SCORE International Baja 1000: The Official Game      PS2
16596  16599                                        Know How 2       DS
16597  16600                                  Spirits & Spells      GBA

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77
1      1985.0      Platform    Nintendo     29.08      3.58      6.81
2      2008.0        Racing    Nintendo     15.85     12.88      3.79
3      2009.0        Sports    Nintendo     15.75     11.01      3.28
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22
...       ...           ...         ...       ...       ...       ...
16593  2002.0      Platform       Kemco      0.01      0.00      0.00
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00
16595  2008.0        Racing  Activision      0.00      0.00      0.00
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00

       Other_Sales  Global_Sales  NAsales_zscore  EUsales_zscore  \
0             8.46         82.74       50.124931       56.689775
1             0.77         40.24       35.035540        6.739150
2             3.31         35.82       18.949106       24.999402
3             2.96         33.00       18.827515       21.327717
4             1.00         31.37       13.380257       17.165165
...            ...           ...             ...             ...
16593         0.00          0.01       -0.310842       -0.290066
16594         0.00          0.01       -0.310842       -0.290066
16595         0.00          0.01       -0.323001       -0.290066
16596         0.00          0.01       -0.323001       -0.270431
16597         0.00          0.01       -0.310842       -0.290066

       JPsales_zscore  Globalsales_zscore  Rank_zscore  Year_zscore
0           11.835234           52.444813    -1.729561    -0.069536
1           21.582588           25.328886    -1.729353    -3.670104
2           11.899361           22.508829    -1.729144     0.273376
3           10.264115           20.709608    -1.728935     0.444831
4           32.516298           19.669632    -1.728727    -1.784092
...               ...                 ...          ...          ...
16593       -0.252768           -0.338732     1.733029    -0.755358
16594       -0.252768           -0.338732     1.733238    -0.583903
16595       -0.252768           -0.338732     1.733446     0.273376
16596       -0.252768           -0.338732     1.733655     0.616287
16597       -0.252768           -0.338732     1.733864    -0.583903

[16291 rows x 17 columns]>
<bound method DataFrame.info of      Rank                                        Name Platform    Year  \
1       2                           Super Mario Bros.      NES  1985.0
5       6                                      Tetris       GB  1989.0
12     13                 Pokemon Gold/Pokemon Silver       GB  1999.0
16     17                          Grand Theft Auto V      PS3  2013.0
18     19                           Super Mario World     SNES  1990.0
..    ...                                         ...      ...     ...
346   347                                Pokemon Snap      N64  1999.0
391   392                                    F-1 Race       GB  1990.0
398   399          The Legend of Zelda: Majora's Mask      N64  2000.0
429   430                           Super Mario Maker     WiiU  2015.0
454   455  The Legend of Zelda: A Link Between Worlds      3DS  2013.0

            Genre             Publisher  NA_Sales  EU_Sales  JP_Sales  \
1        Platform              Nintendo     29.08      3.58      6.81
5          Puzzle              Nintendo     23.20      2.26      4.22
12   Role-Playing              Nintendo      9.00      6.18      7.20
16         Action  Take-Two Interactive      7.01      9.27      0.97
18       Platform              Nintendo     12.78      3.75      3.54
..            ...                   ...       ...       ...       ...
346    Simulation              Nintendo      2.23      0.68      0.66
391        Racing              Nintendo      1.73      0.69      0.59
398        Action              Nintendo      1.90      0.67      0.73
429      Platform              Nintendo      1.18      0.87      0.93
454        Action              Nintendo      1.40      0.99      0.46

     Other_Sales  Global_Sales
1           0.77         40.24
5           0.58         30.26
12          0.71         23.10
16          4.14         21.40
18          0.55         20.61
..           ...           ...
346         0.06          3.63
391         0.40          3.41
398         0.06          3.36
429         0.20          3.18
454         0.22          3.07

[62 rows x 11 columns]>

In [197]:
# there are two categories which are numbers (floats + integers) and strings 
#the columns we need to adjust it's type are Name , Platform , Genre and Publisher 
# the frequent tags  
genrelist = df.Genre.values
namelist = df.Name.values
pllist = df.Platform.values
publist = df.Publisher.values
def get_most_frequent (list,name):
    df2 = pd.DataFrame( list , columns = ['data'])
    mostfrequent = [df2.data.value_counts()] 
    return (mostfrequent)
# tags 
generTags = list(dict.fromkeys(df.Genre.values))
nameTags = list(dict.fromkeys(df.Name.values))
platformTag = list(dict.fromkeys(df.Platform.values))
publisherTag = list(dict.fromkeys(df.Publisher.values))

print(get_most_frequent(genrelist,'gener'))
print(get_most_frequent(namelist,'name'))
print(get_most_frequent(pllist,'platform'))
print(get_most_frequent(publist,'publisher'))

[Platform        18
Action          13
Role-Playing     8
Racing           8
Fighting         6
Puzzle           3
Strategy         2
Adventure        1
Misc             1
Shooter          1
Simulation       1
Name: data, dtype: int64]
[Tetris                                        2
Super Smash Bros. for Wii U and 3DS           2
The Legend of Zelda: A Link to the Past       1
Resident Evil 2                               1
Tekken 2                                      1
Pokemon Stadium                               1
Dr. Mario                                     1
Pokemon Pinball                               1
Final Fantasy IX                              1
Donkey Kong 64                                1
Super Mario Land 3: Wario Land                1
Donkey Kong Country 2: Diddy's Kong Quest     1
Resident Evil                                 1
Diddy Kong Racing                             1
Crash Team Racing                             1
Super Mario Bros.                             1
Metal Gear Solid                              1
Splatoon                                      1
Super Mario 3D World                          1
Tekken Tag Tournament                         1
Donkey Kong Land                              1
The Legend of Zelda: Link's Awakening         1
Resident Evil Director's Cut                  1
Resident Evil 3: Nemesis                      1
Pokémon Trading Card Game                     1
Banjo-Kazooie                                 1
Pokemon Snap                                  1
F-1 Race                                      1
The Legend of Zelda: Majora's Mask            1
Super Mario Maker                             1
Luigi's Mansion: Dark Moon                    1
Street Fighter II: The World Warrior          1
Pokémon Crystal Version                       1
The Legend of Zelda                           1
Pokemon Gold/Pokemon Silver                   1
Grand Theft Auto V                            1
Super Mario World                             1
Super Mario Land                              1
Super Mario Bros. 3                           1
Pokémon Yellow: Special Pikachu Edition       1
Pokemon X/Pokemon Y                           1
Super Mario 64                                1
Pokemon Omega Ruby/Pokemon Alpha Sapphire     1
Super Mario Land 2: 6 Golden Coins            1
Gran Turismo                                  1
Super Mario All-Stars                         1
Mario Kart 64                                 1
Final Fantasy VII                             1
Gran Turismo 2                                1
Donkey Kong Country                           1
Super Mario Kart                              1
Final Fantasy VIII                            1
The Legend of Zelda: Ocarina of Time          1
Crash Bandicoot 2: Cortex Strikes Back        1
Super Mario Bros. 2                           1
Tekken 3                                      1
Crash Bandicoot 3: Warped                     1
Mario Kart 8                                  1
Crash Bandicoot                               1
The Legend of Zelda: A Link Between Worlds    1
Name: data, dtype: int64]
[PS      16
GB      13
N64      9
SNES     7
NES      5
3DS      5
WiiU     5
PS3      1
PS2      1
Name: data, dtype: int64]
[Nintendo                        43
Sony Computer Entertainment      9
Virgin Interactive               3
SquareSoft                       2
Take-Two Interactive             1
Capcom                           1
Konami Digital Entertainment     1
Namco Bandai Games               1
Eidos Interactive                1
Name: data, dtype: int64]